apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: prod-env
data:
  MONGO_INITDB_ROOT_USERNAME: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: prod-env
type: Opaque
# stringData:
#   # Kubernetes will automatically base64 encode this stringData for you
#   MONGO_INITDB_ROOT_PASSWORD: "late2dine"
data:
# [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("late2dine"))
  MONGO_INITDB_ROOT_PASSWORD: bGF0ZTJkaW5l